services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build: .
    command: fastapi run src/main.py --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env